language: node_js
node_js: stable

install:
  - npm install 
  
script:
  - hexo cl
  - hexo g

after_script:
  - cd ./public
  - git init
  - git config user.name "zhengkd95"
  - git config user.email "zkd17@mails.tsinghua.edu.cn"
  - echo 'www.kedi-zheng.com' > CNAME
  - git add .
  - git commit -m "travis ci auto build"
  - git push --force --quiet "https://${personal_access_token}@$GH_ref" master:master

branches:
  only:
    - hexo 
  global:
    - GH_ref: github.com/zhengkd95/zhengkd95.github.io.git

